name: Gradle Build

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  gradle-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    env:
      DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: ':(gradm|initialization|project)'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          validate-wrappers: true
          dependency-graph: generate-and-upload

      - run: ./gradlew build --no-daemon --stacktrace

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./wwm/web/build/dist/wasmJs/productionExecutable

  gradle-submit-dependency-graph:
    name: Gradle Submit Dependency Graph
    uses: OmicoDev/gradle-project-initializer-template/.github/workflows/gradle-submit-dependency-graph.yml@main
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: gradle-build
    permissions:
      contents: write

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
